name: namer_app
description: A new Flutter project that generates random word pairs.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Setting for Dart 3

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0  # Latest version compatible with Dart 3
  provider: ^6.0.5      # Latest version for state management
  cupertino_icons: ^1.0.6  # Optional - for iOS style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Recommended for Dart 3

flutter:
  uses-material-design: true